"""Initial migration

Revision ID: d427554387e7
Revises: 
Create Date: 2025-10-03 01:00:25.404613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd427554387e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=5000), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('about_product', sa.String(length=6000), nullable=True),
    sa.Column('rating', sa.Numeric(), nullable=True),
    sa.Column('rating_count', sa.Numeric(), nullable=True),
    sa.Column('discount_percentage', sa.Text(), nullable=True),
    sa.Column('actual_price', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Numeric(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_ip', sa.String(length=100), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=100), nullable=True),
    sa.Column('clean_review_text', sa.Text(), nullable=True),
    sa.Column('duplicate_review_score', sa.Float(), nullable=True),
    sa.Column('suspicion_score_weighted', sa.Float(), nullable=True),
    sa.Column('flag_reasons', sa.Text(), nullable=True),
    sa.Column('rule_rate_limit', sa.Numeric(), nullable=True),
    sa.Column('rule_new_account_extreme', sa.Numeric(), nullable=True),
    sa.Column('rule_duplicate_text', sa.Numeric(), nullable=True),
    sa.Column('rule_vpn_ip', sa.Numeric(), nullable=True),
    sa.Column('rule_same_device', sa.Numeric(), nullable=True),
    sa.Column('rule_low_quality', sa.Numeric(), nullable=True),
    sa.Column('rule_burst_activity', sa.Numeric(), nullable=True),
    sa.Column('is_fake_ml', sa.Numeric(), nullable=True),
    sa.Column('ml_confidence', sa.Float(), nullable=True),
    sa.Column('is_fake_behavioral', sa.Numeric(), nullable=True),
    sa.Column('behavioral_flags', sa.Text(), nullable=True),
    sa.Column('behavioral_score', sa.Float(), nullable=True),
    sa.Column('is_fake', sa.Numeric(), nullable=True),
    sa.Column('is_fake_rule_based', sa.Numeric(), nullable=True),
    sa.Column('label_source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
